version: build-{build}
branches:
  only:
  - master
image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true
pull_requests:
  do_not_increment_build_number: true
clone_folder: C:\LibraryBase

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
init:
- ps: $Env:BUILD = "$($Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0"))"

build_script:
- ps: appveyor-retry dotnet restore Akitaux.LibraryBase.sln -v Minimal /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet build Akitaux.LibraryBase.sln -c "Release" /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"

after_build:
- ps: dotnet pack "src\Akitaux.LibraryBase.Core\Akitaux.LibraryBase.Core.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: dotnet pack "src\Akitaux.LibraryBase.Rest\Akitaux.LibraryBase.Rest.csproj" -c "Release" -o "../../artifacts" --no-build /p:BuildNumber="$Env:BUILD" /p:IsTagBuild="$Env:APPVEYOR_REPO_TAG"
- ps: Get-ChildItem artifacts\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
- provider: NuGet
  server: https://www.myget.org/F/akitaux/api/v2/package
  api_key:
    secure: package_limited_token
  symbol_server: https://www.myget.org/F/akitaux/api/v2/package
  on:
    branch: master